{
  "hash": "1f471f83128813690717a8c9f0d660eb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Why Do People Leave Their Jobs? An Analysis of ENOE 2025 Q1\"\ndescription: \"A tutorial on how to carry out a complex survey analysis with R, using data from ENOE 2025.\"\nauthor: \"Karen Sánchez\"\ndate: \"2025-07-09\"\nimage: \"img.jpg\"\nformat: html\neditor: visual\n---\n\n\n\n\n## Introduction\n\nEmployment transitions are an important indicator of labor market dynamics. Understanding why workers resign or lose their jobs provides valuable information for economists, policymakers, and businesses.\n\nIn this project, we analyzed data from the 2025 Q1 National Occupation and Employment Survey (ENOE) published by INEGI. Because ENOE uses a complex probabilistic sampling design, the analysis is performed with the survey package in R to produce nationally representative estimates.\n\nSpecifically, this report aims to answer these questions:\n\n1)  Why do people voluntarily resign?\n2)  Why do people lose their jobs?\n3)  Do the reasons for unemployment differ between men and women?\n\n## Surveys and Complex Samples\n\nAs mentioned earlier, we're going to analyze data from ENOE, which is conducted by the National Institute of Statistics and Geography (INEGI). In order to conduct a national survey you may imagine that is nearly impossible to interview all inhabitants of a country because of monetary and time costs, so it is necessary to rely on a probabilistic complex sampling design that allows accurate estimation of population characteristics while reducing costs.\n\nA sample can give us good estimates of the whole population. For example, if we want to know the average height of students in a university, a sample created by a random selection of students will be sufficient to give us an approximation of the real average height of the whole university. However, the sample of a national survey can't be that simple, since it needs to represent the behavior of people with different characteristics throughout a country and variables under study can vary greatly from North to South, or from rural to urban areas or depend on socioeconomic status of the people. In order to provide estimates of different population clusters, we need to work with a complex sample.\n\nComplex samples allows to represent subgroups of a population better than a simple random sample. Unlike a simple random sample, where all units of a population have the same probability of being selected, in a complex sample, units are drawn following a multiple stage process. In the case of ENOE, it consists on two stages. First of all, the National Institute of Statistics and Geography selects a master sample of Primary Sample Units (PSUs) with a probability proportional to the number of registered households in the most recent Census of Population and Housing. Next, a subsample of PSUs is selected with equal probability for each stratum. Finally, households are selected with the same probability for each PSU.\n\nPSUs are created by INEGI using cartographic and demographic information from the latest Census of Population and Housing. A PSU is classified by federative entity, size of the area (rural, urban or urban's complement) and sociodemographic conditions of households.\n\nA stratum is a group of people that share a common trait, it can be age, gender, race or it can be a geographic or temporal feature. Strata are useful in surveys to obtain insights of these groups, since observations of the complete population wouldn't be so valuable.\n\nStratification in ENOE is sociodemographic. There are four strata: low, middle-low, middle-high, and high. They are created by a statistical summary of 34 indicators that involves household's physical attributes and equipment, as well as sociodemographic features of the household members.\n\nWeights or expansion factors are used to represent the correct number of people in a population. They are given as the inverse of the probability of selection of respondents. They are also crucial to adjust for nonresponse and oversampling.\n\nThere are some subpopulations that need to be oversampled, that is, giving them a greater chance of selection, because originally they were less likely to be chosen due to the smallness of the subpopulations or because they are hard-to-reach, such as the elderly, children or people living in rural areas. Later, at the estimation stage, in order to obtain results for the population, rather than just the sample, we use weights to compensate for oversampling.\n\n## Data Preprocessing\n\nWe're interested in analyzing the reasons people voluntary left or lost a job with data from Q1 ENOE 2025. This information is contained in the database of ENOE's basic questionnaire part 2 of the corresponding period of time, specifically, at questions 9, 9a, 9b, 9c and 9d.\n\n![](p9.png)\n\n![](p9a.png)\n\n![](p9a.png)\n\n![](p9b.png)\n\n![](p9c.png)\n\n![](p9d.png)\n\nWe start by loading the dataset corresponding to the second part of the questionnaire and the one with the sociodemographic variables of participants.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LOADING DATA SETS\ncoe2 <- read.csv(\"~/my-r-nbs/ENOE/conjunto_de_datos_coe2_enoe_2025_1t/conjunto_de_datos/conjunto_de_datos_coe2_enoe_2025_1t.csv\", header = TRUE, sep = \",\", stringsAsFactors = FALSE)\nsdem <- read.csv(\"~/my-r-nbs/ENOE/conjunto_de_datos_sdem_enoe_2025_1t/conjunto_de_datos/conjunto_de_datos_sdem_enoe_2025_1t.csv\", header = TRUE, sep = \",\", stringsAsFactors = FALSE)\n```\n:::\n\n\n\n\nTo improve readability throughout the analysis, categorical variables are converted from numeric codes into descriptive factor labels.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoe2$p9_f_EverUnemployed <- factor(\n  coe2$p9,\n  levels = c(1,2,9),\n  labels = c(\"Yes\",\"No\",\"Doesn't Know\")\n)\ncoe2$p9a_f_UnemployReason <- factor(\n  coe2$p9a,\n  levels = 1:9,\n  labels = c(\n    \"Job loss\",\n    \"Resigned\", \n    \"Business closure\",\n    \"Retirement\",\n    \"Accident/injury\",\n    \"Deportation from USA\",\n    \"Job affected by disasters\",\n    \"None of the above\",\n    \"Doesn't know\"\n  )\n)\ncoe2$p9b_f_JobLossCause <- factor(\n  coe2$p9b,\n  levels = c(1, 2, 3, 4, 5, 6, 7, 9),\n  labels = c(\n    \"The workplace closed or went bankrupt\",\n    \"There was a layoff / downsizing\",\n    \"The company relocated to another city or country\",\n    \"Contract was not renewed\",\n    \"Was not called back\",\n    \"Was fired\",\n    \"None of the above\",\n    \"Doesn't know\"\n  )\n)\ncoe2$p9c_f_ServiceTerminationReason <- factor(\n  coe2$p9c,\n  levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 99),\n  labels = c(\n    \"Labor or union conflict\",\n    \"Conflict with boss or supervisor\",\n    \"Lack of qualifications or training\",\n    \"No more work available\",\n    \"Breach of contract\",\n    \"Discrimination based on appearance\",\n    \"Age (too young or too old)\",\n    \"Illness or disability\",\n    \"Pregnancy and/or maternal responsibilities\",\n    \"None of the above\",\n    \"Doesn't know\"\n  )\n)\ncoe2$p9d_f_MainExitMotive <- factor(\n  coe2$p9d,\n  levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 99),\n  labels = c(\n    \"Wanted to earn more\",\n    \"Wanted independence\",\n    \"Change or worsening in work conditions\",\n    \"Risky and/or unhealthy work\",\n    \"Was forced to resign or retire\",\n    \"Lack of opportunities for advancement\",\n    \"Harassment or lack of respect\",\n    \"Conflict with boss or supervisor\",\n    \"Marriage, pregnancy, or family responsibilities\",\n    \"Family member prevented continuation\",\n    \"Wanted to keep studying\",\n    \"None of the above\",\n    \"Doesn't know\"\n  ))\nsdem$sex_f <- factor(\n  sdem$sex,\n  levels = c(1,2),\n  labels = c(\"Man\",\"Woman\")\n)\n```\n:::\n\n\n\n\nWe merge the datasets using the primary key composed by tipo+ent+v_sel+n_hogar+h_mud+n_ren. This provides access to sociodemographic variables together with sample weights (`fac_tri`) and strata (`est_d_tri`), required for sample design. From the questionnaire dataset, we keep only the variables corresponding to the questions we're analyzing, `exit_motives_vars`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_key <- c(\"tipo\", \"ent\", \"con\", \"v_sel\", \"n_hog\", \"h_mud\", \"n_ren\")\n# From the questionnaire, we keep just the questions related to events of \n# job loss or resignation\nexit_motives_vars <- c(\n  \"p9\",\n  \"p9_f_EverUnemployed\",\n  \"p9a\",\n  \"p9a_f_UnemployReason\",\n  \"p9b\",\n  \"p9b_f_JobLossCause\",\n  \"p9c\",\n  \"p9c_f_ServiceTerminationReason\",\n  \"p9d\",\n  \"p9d_f_MainExitMotive\"\n)\nExitMotives_df <- merge(\n  sdem[,c(primary_key,\"eda\",\"sex\",\"sex_f\",\"r_def\",\"c_res\",\"upm\",\"est_d_tri\",\"fac_tri\")],\n  coe2[,c(primary_key,exit_motives_vars)],\n  by=primary_key\n)\n```\n:::\n\n\n\n\n## Library `survey`\n\nR comes with a dedicated library for statistical analysis of complex survey samples, named `survey`. As you can recall, the essential components to define the sample design are PSUs, strata, and weights. Then,`survey` requires this data in order to be ready to compute statistical correct results.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install survey, if you haven't already.\n# install.packages('survey')\n\n# Load library\nlibrary(survey)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: Matrix\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: survival\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'survey'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:graphics':\n\n    dotchart\n```\n\n\n:::\n\n```{.r .cell-code}\n# Definition of the sample design object\n# ids = ~upm     -> PSUs\n# strata = ~est_d_tri  -> Q1 2025 design strata\n# weights = ~fac_tri -> Q1 2025 weights or expansion factors\n# nest = TRUE        -> It means that IDs are repeated between strata\n# data = ExitMotives_df  -> Our data\nsdem_design <- svydesign(\n  ids = ~upm,\n  strata = ~est_d_tri,\n  weights = ~fac_tri,\n  nest = TRUE,\n  data = ExitMotives_df\n)\n```\n:::\n\n\n\n\nWe use the next command to handle strata with a single PSU.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(survey.lonely.psu=\"adjust\")\n```\n:::\n\n\n\n\n### Proportions\n\nThe subpopulation we're interested in is people aged 15 and older and habitual residents of a household (c_res=1). `r_def=0` refers to respondent with finished interview. We create this subpopulation with `subset`, whose arguments are the survey design object and the expression to filter data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsdem_subpop <- subset(sdem_design,  eda>=15 & eda<=98 & r_def==0 & c_res==1)\n```\n:::\n\n\n\n\nWe're now ready to begin the data analysis.\n\n## Exploratory Data Analysis\n\n### First question: Why do people voluntarily leave their job?\n\nWe filter the data again to include only participants with meaningful answers, then, we will discard people who answered \"None of the above\" and \"Doesn't know\". Furthermore, we retain only respondents whose reason to be unemployed was quitting (p9a=2). We also filter out people who didn't get ask this question, that is, missing values.\n\nWe load library `dplyr` for data manipulation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nresign_subpop <- subset(sdem_subpop, p9a == 2 & !is.na(p9d) & p9d != 99 & p9d != 12)\n```\n:::\n\n\n\n\nWe use the function `svymean` to compute proportions of the variable to be analyzed.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresign_motives_proportions <- svymean(~p9d_f_MainExitMotive, resign_subpop, na.rm=TRUE)\nresign_motives_proportions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                         mean\np9d_f_MainExitMotiveWanted to earn more                             0.1838357\np9d_f_MainExitMotiveWanted independence                             0.0668695\np9d_f_MainExitMotiveChange or worsening in work conditions          0.1067129\np9d_f_MainExitMotiveRisky and/or unhealthy work                     0.0152641\np9d_f_MainExitMotiveWas forced to resign or retire                  0.0043506\np9d_f_MainExitMotiveLack of opportunities for advancement           0.0094913\np9d_f_MainExitMotiveHarassment or lack of respect                   0.0114692\np9d_f_MainExitMotiveConflict with boss or supervisor                0.0329812\np9d_f_MainExitMotiveMarriage, pregnancy, or family responsibilities 0.4572812\np9d_f_MainExitMotiveFamily member prevented continuation            0.0321391\np9d_f_MainExitMotiveWanted to keep studying                         0.0796053\np9d_f_MainExitMotiveNone of the above                               0.0000000\np9d_f_MainExitMotiveDoesn't know                                    0.0000000\n                                                                        SE\np9d_f_MainExitMotiveWanted to earn more                             0.0034\np9d_f_MainExitMotiveWanted independence                             0.0025\np9d_f_MainExitMotiveChange or worsening in work conditions          0.0025\np9d_f_MainExitMotiveRisky and/or unhealthy work                     0.0010\np9d_f_MainExitMotiveWas forced to resign or retire                  0.0005\np9d_f_MainExitMotiveLack of opportunities for advancement           0.0008\np9d_f_MainExitMotiveHarassment or lack of respect                   0.0008\np9d_f_MainExitMotiveConflict with boss or supervisor                0.0014\np9d_f_MainExitMotiveMarriage, pregnancy, or family responsibilities 0.0042\np9d_f_MainExitMotiveFamily member prevented continuation            0.0016\np9d_f_MainExitMotiveWanted to keep studying                         0.0022\np9d_f_MainExitMotiveNone of the above                               0.0000\np9d_f_MainExitMotiveDoesn't know                                    0.0000\n```\n\n\n:::\n:::\n\n\n\n\nYou can notice that the advantage of creating categorical variables is the ease of interpretation of results, as we can directly see the labels, therefore we don't have to worry about forgetting which response stands for which numeric code.\n\nLet's make a horizontal bar chart to visualize the above results with gg2plot. First, we convert the results into a dataframe, because this way is easier for gg2plot to use.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the necessary libraries\nlibrary(ggplot2)\nlibrary(forcats) # For reordering factor levels\nlibrary(scales) # For formatting numbers as percentages\n\n# Create a dataframe\nresign_df <- data.frame(\n  Motive = gsub(\"p9d_f_MainExitMotive\",\"\",names(coef(resign_motives_proportions))),\n  Proportion = as.numeric(coef(resign_motives_proportions))) %>%\n    # Rearranged data for clarity\n    arrange(desc(Proportion))\n\n# Create the plot\nexit_motive_plot <- resign_df %>%\n  # Use fct_reorder() to sort the bars from highest to lowest proportion\n  mutate(Motive = fct_reorder(Motive, Proportion)) %>%\n  ggplot(aes(x = Motive, y = Proportion)) +\n  \n  # Use geom_col() for the bar chart. A single, strong color is often best.\n  geom_col(fill = \"#0072B2\", alpha = 0.9) +\n  \n  # Flip coordinates to make the bar chart horizontal\n  coord_flip() +\n  \n  # Add text labels showing the exact percentage on each bar\n  geom_text(\n    aes(label = percent(Proportion, accuracy = 0.1)), \n    hjust = -0.15, # Pushes the label just outside the bar\n    size = 3.5,\n    fontface = \"bold\",\n    color = \"gray20\"\n  ) +\n  \n  # Format the Y-axis to show percentages and expand it to make room for labels\n  scale_y_continuous(\n    labels = percent_format(),\n    expand = expansion(mult = c(0, .15)) # Give 15% extra space on the right\n  ) +\n  \n  # Add informative titles, subtitles, and a caption\n  labs(\n    title = \"Why Did You Leave? Top Reasons for Resigning in Mexico\",\n    subtitle = \"Analysis of individuals aged 15+ who left their job, Q1 2025\",\n    x = \"\", # The y-axis labels are self-explanatory, so we remove the axis title\n    y = \"Percentage of Respondents\",\n    caption = \"Source: INEGI, Encuesta Nacional de Ocupación y Empleo (ENOE), Q1 2025. Results calculated using survey weights.\"\n  ) +\n  \n  # Apply a clean, professional theme\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 18),\n    plot.subtitle = element_text(size = 12, color = \"gray30\"),\n    plot.caption = element_text(hjust = 0, color = \"gray50\", margin = margin(t = 15)),\n    panel.grid.major.y = element_blank(), # Remove horizontal grid lines for a cleaner look\n    panel.grid.minor.x = element_blank(),\n    axis.text.y = element_text(size = 11),\n    axis.title.x = element_text(face = \"bold\", margin = margin(t = 10))\n  )\n\n# Display the plot\nexit_motive_plot\n```\n\n::: {.cell-output-display}\n![](complex_samples_with_R_files/figure-html/exit-motive-plot-1.png){width=1152}\n:::\n:::\n\n\n\n\nThese results suggest that family obligations are by far the primary resignation driver, accounting for nearly half of all responses in the first quarter of 2025. The other two most prominent reasons are salary and environment, highlighting that when workers leave due to work-specific reasons, wage improvement (18.4%) and deteriorating conditions (10.7%) are substantially more common triggers than interpersonal workplace friction or harassment.\n\n### Second question: Why do people lose their job?\n\nWe are only keeping those people with a specific reason they lost their job. Also, they have to give as a reson of unemployment the answer \"Job Loss\" (p9a=1).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\njobloss_subpop <- subset(sdem_design, p9a == 1 & p9b !=7 & p9b != 9)\n# proportions computed with svymean\njoblosscauses_proportions <- svymean(~p9b_f_JobLossCause, jobloss_subpop, na.rm=TRUE)\njoblosscauses_proportions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                       mean\np9b_f_JobLossCauseThe workplace closed or went bankrupt            0.215990\np9b_f_JobLossCauseThere was a layoff / downsizing                  0.373416\np9b_f_JobLossCauseThe company relocated to another city or country 0.011153\np9b_f_JobLossCauseContract was not renewed                         0.103897\np9b_f_JobLossCauseWas not called back                              0.170339\np9b_f_JobLossCauseWas fired                                        0.125205\np9b_f_JobLossCauseNone of the above                                0.000000\np9b_f_JobLossCauseDoesn't know                                     0.000000\n                                                                       SE\np9b_f_JobLossCauseThe workplace closed or went bankrupt            0.0045\np9b_f_JobLossCauseThere was a layoff / downsizing                  0.0057\np9b_f_JobLossCauseThe company relocated to another city or country 0.0016\np9b_f_JobLossCauseContract was not renewed                         0.0031\np9b_f_JobLossCauseWas not called back                              0.0047\np9b_f_JobLossCauseWas fired                                        0.0037\np9b_f_JobLossCauseNone of the above                                0.0000\np9b_f_JobLossCauseDoesn't know                                     0.0000\n```\n\n\n:::\n:::\n\n\n\n\nLet's make another horizontal bar plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a dataframe, since it is easier to interpret by gg2plot\njoblosscauses_df <- data.frame(\n  Proportion = coef(joblosscauses_proportions)\n) %>%\n  tibble::rownames_to_column(var=\"Cause\") %>%\n  mutate(\n    Motive = gsub(\"p9b_f_JobLossCause\",\"\",Cause)\n  ) %>%\n  arrange(desc(Proportion))\n# create the plot\njob_loss_plot <- joblosscauses_df %>%\n  # Use fct_reorder() to sort the bars from highest to lowest proportion\n  mutate(Motive = fct_reorder(Motive, Proportion)) %>%\n  ggplot(aes(x = Motive, y = Proportion)) +\n  \n  # Use geom_col() for the bar chart. A single, strong color is often best.\n  geom_col(fill = \"#0072B2\", alpha = 0.9) +\n  \n  # Flip coordinates to make the bar chart horizontal\n  coord_flip() +\n  \n  # Add text labels showing the exact percentage on each bar\n  geom_text(\n    aes(label = percent(Proportion, accuracy = 0.1)), \n    hjust = -0.15, # Pushes the label just outside the bar\n    size = 3.5,\n    fontface = \"bold\",\n    color = \"gray20\"\n  ) +\n  \n  # Format the Y-axis to show percentages and expand it to make room for labels\n  scale_y_continuous(\n    labels = percent_format(),\n    expand = expansion(mult = c(0, .15)) # Give 15% extra space on the right\n  ) +\n  \n  # Add informative titles, subtitles, and a caption\n  labs(\n    title = \"Why Did You Lose Your Job? Top Reasons for Losing Job in Mexico\",\n    subtitle = \"Analysis of individuals aged 15+ who lost their job, Q1 2025\",\n    x = \"\", # The y-axis labels are self-explanatory, so we remove the axis title\n    y = \"Percentage of Respondents\",\n    caption = \"Source: INEGI, Encuesta Nacional de Ocupación y Empleo (ENOE), Q1 2025.\\nResults calculated using survey weights.\"\n  ) +\n  \n  # Apply a clean, professional theme\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 18),\n    plot.subtitle = element_text(size = 12, color = \"gray30\"),\n    plot.caption = element_text(hjust = 0, color = \"gray50\", margin = margin(t = 15)),\n    panel.grid.major.y = element_blank(), # Remove horizontal grid lines for a cleaner look\n    panel.grid.minor.x = element_blank(),\n    axis.text.y = element_text(size = 11),\n    axis.title.x = element_text(face = \"bold\", margin = margin(t = 10))\n  )\n\n# Display the plot\nprint(job_loss_plot)\n```\n\n::: {.cell-output-display}\n![](complex_samples_with_R_files/figure-html/job-loss-plot-1.png){width=1152}\n:::\n:::\n\n\n\n\nThe two main drivers are related to structural economic pressures, such as, corporate restructuring, downsizing and business closures, that jointly account for 58.9% of total job loss, while temporary contracts (\"Was not called back\" and \"Contract was not renewed\") represent 27.4% of job losses, underscoring systemic job insecurity in the Mexican labor market.\n\n### Third question: Why do people become unemployed? Reasons by gender.\n\nHere we're going to use a new function,`svyby`, which performs cross tabulations.\n\nFirst, we filter out the individuals who didn't get asked this question (question 9a) and retain people who gave an informative answer and reported to be unemployed someday (p9=1).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunemployreason_subpop <- subset(sdem_subpop, !is.na(p9a) & p9a != 8 & p9a != 9)\n```\n:::\n\n\n\n\n`svyby` will create a cross tabulation of reasons of unemployment by gender.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunemployreason_by_gender <- svyby(\n  ~p9a_f_UnemployReason,\n  by = ~sex_f,\n  design = unemployreason_subpop,\n  FUN = svymean,\n  keep.var = FALSE\n)\n```\n:::\n\n\n\n\nNow we'll convert the above result from wide format to a long format:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load library \nlibrary(tidyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'tidyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:Matrix':\n\n    expand, pack, unpack\n```\n\n\n:::\n\n```{.r .cell-code}\nunemployreason_long <- unemployreason_by_gender %>%\n  # Convertir el objeto svy a un data frame estándar\n  as.data.frame() %>%\n  # La función `pivot_longer` transforma los datos del formato wide al long\n  pivot_longer(\n    cols = -sex_f,\n    names_to = \"Motive\",\n    values_to = \"Proportion\"\n  ) %>%\n  # Limpia los nombres de las columnas y valores para claridad\n  mutate(\n    Motive = gsub(\"statistic\\\\.|p9a_f_UnemployReason\",\"\",Motive),\n    # Renombrar la columna `sex_f` para que sea más descriptiva\n    Gender = sex_f\n  ) %>%\n  # Seleccionar y reordenar las columnas finales para el CSV\n  select(Gender, Motive, Proportion)\n# Reorder motives by average proportion across genders\nunemployreason_long <- unemployreason_long %>%\n  group_by(Motive) %>%\n  mutate(avg_prop = mean(Proportion)) %>%\n  ungroup() %>%\n  mutate(Motive = reorder(Motive, -avg_prop))  # Descending order\n```\n:::\n\n\n\n\nLet's create the visualization\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reorder unemployment reasons by their average proportion across genders\nunemployreason_long <- unemployreason_long %>%\n  group_by(Motive) %>%\n  mutate(avg_prop = mean(Proportion)) %>%\n  ungroup() %>%\n  mutate(Motive = fct_reorder(Motive, avg_prop))\n\n# Create the plot\nunemployment_gender_plot <- ggplot(\n  unemployreason_long,\n  aes(x = Motive, y = Proportion, fill = Gender)\n) +\n  \n  # Grouped bars for gender comparison\n  geom_col(\n    position = position_dodge(width = 0.8),\n    width = 0.7\n  ) +\n  \n  # Add percentage labels\n  geom_text(\n    aes(\n      label = percent(Proportion, accuracy = 0.1)\n    ),\n    position = position_dodge(width = 0.8),\n    hjust = -0.15,\n    size = 3.2,\n    fontface = \"bold\",\n    color = \"gray20\"\n  ) +\n  \n  # Flip coordinates to improve readability of long category labels\n  coord_flip() +\n  \n  # Format the axis as percentages\n  scale_y_continuous(\n    labels = percent_format(),\n    expand = expansion(mult = c(0, .15))\n  ) +\n  \n  # Titles and labels\n  labs(\n    title = \"Reasons for Unemployment by Gender in Mexico\",\n    subtitle = \"Analysis of individuals aged 15+ with a reported reason for unemployment, Q1 2025\",\n    x = \"\",\n    y = \"Percentage of Respondents\",\n    fill = \"Gender\",\n    caption = \"Source: INEGI, Encuesta Nacional de Ocupación y Empleo (ENOE), Q1 2025.\\nResults calculated using survey weights.\"\n  ) +\n  \n  # Apply the same visual style as the other plots\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(\n      face = \"bold\",\n      size = 18\n    ),\n    plot.subtitle = element_text(\n      size = 12,\n      color = \"gray30\"\n    ),\n    plot.caption = element_text(\n      hjust = 0,\n      color = \"gray50\",\n      margin = margin(t = 15)\n    ),\n    \n    # Remove unnecessary grid lines\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor.x = element_blank(),\n    \n    axis.text.y = element_text(\n      size = 10\n    ),\n    \n    axis.title.x = element_text(\n      face = \"bold\",\n      margin = margin(t = 10)\n    ),\n    \n    # Place legend above the plot, similar to the title hierarchy\n    legend.position = \"top\",\n    legend.title = element_text(face = \"bold\")\n  )\n\n# Display the plot\nprint(unemployment_gender_plot)\n```\n\n::: {.cell-output-display}\n![](complex_samples_with_R_files/figure-html/unemployment-gender-plot-1.png){width=1152}\n:::\n:::\n\n\n\n\nResigned (voluntary departure) represents the largest category for both genders, but show a massive gender gap. Over half of unemployed women (55.1%) left their jobs voluntarily, compared to 32.7% of men. On the other hand, job loss (involutary displacement) is as important as the main driver for men, whereas for women it accounts for less than a fifth (19.6%) of unemployed women. We can also appreciate that males (20.8%) are nearly twice as likely to cite retirement as their reason for unemployment compared to females (10.5%).\n\n# Conclusions\n\nThis analysis demonstrates how complex survey methods can be applied to obtain nationally representative estimates from ENOE. Using the survey package, we explored the main reasons behind job resignation and job loss in Mexico during the first quarter of 2025.\n\nThe workflow presented here—including data preprocessing, survey design specification, weighted estimation, and visualization—can be extended to investigate many other labor market questions contained in ENOE.\n",
    "supporting": [
      "complex_samples_with_R_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}